# Running a CRON job using GitHub Actions

on:
  schedule:
    # Configure the CRON schedule for the job. The job will run every day at midnight.
    - cron: '0 17 * * *'

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      # Make an HTTP request to the REST API endpoint using the `curl` command
      - name: Send request to REST API
        run: curl -X GET https://lele.deta.dev/kurangi_stock_pakan_harian
