# Running a CRON job using GitHub Actions

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      # Make an HTTP request to the REST API endpoint using the `curl` command
      - name: Send request to REST API
        run: curl -X GET https://lele.deta.dev/proses_notifikasi